package Security

import (
	"Framework/Helpers"
	"net/http"
	"strings"
)

// The bearer token is a cryptic string, usually generated by the server in response to a login request. The client must send this token in the Authorization header
type AuthenticationBearer struct {
}

func (s AuthenticationBearer) GetToken(HttpRequest *http.Request) string {
	authorizationToken := HttpRequest.Header.Get("Authorization")
	if !Helpers.IsEmpty(authorizationToken) {
		splitToken := strings.Split(authorizationToken, "Bearer")
		if len(splitToken) > 0 {
			authorizationToken = strings.TrimSpace(splitToken[1])
		}
	}
	return authorizationToken
}
